### ISSUE TITLE
Method not found error when trying to browse swagger

### ISSUE THREAD

**Issue by mateusz-kula** [rflechner/Suave.Swagger#8] opened 2017-01-14 20:21 UTC
I am getting error below when trying to browse http://localhost:9000/swagger/v2/ui/index.html
I created a new project in Visual Studio 2015 with F# 4 on .NET 4.6.1 and Suave 2
The same behaviour is with my code and petstore sample. 
Thanks in advance for help!

Method not found: 'HttpContent HttpContent.NewSocketTask(Microsoft.FSharp.Core.FSharpFunc`2,Microsoft.FSharp.Control.FSharpAsync`1>>)'.

System.MissingMethodException: Method not found: 'HttpContent HttpContent.NewSocketTask(Microsoft.FSharp.Core.FSharpFunc`2,Microsoft.FSharp.Control.FSharpAsync`1>>)'. at Suave.Swagger.Swagger.streamZipContent$cont@407(String swJsonPath, HttpContext ctx, String p, Stream fs, ZipInputStream zip, Unit unitVar) at Suave.Swagger.Swagger.wp@392.Invoke(HttpContext ctx) in D:\temp\28162aa\src\Suave.Swagger\Swagger.fs:line 407 at Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a)

**Comment by alexey-belous** [comment] 2017-01-25 10:16
@mateusz-kula, I faced with this issue too. It seems that Suave.Swagger currently doesn't support Suave 2.X.

**Comment by rkosafo** [comment] 2017-02-15 11:40
Just tested and got the same issue. I see a PR with `Suave 2.x` support. Is it ready? Any when it will be available in the nuget package? If not, any workaround?

**Comment by alexey-belous** [comment] 2017-02-15 14:46
@rkosafo, PR is ready, but it seems that maintainer still hasn't merged it. So, there are two workarounds: downgrade Suave to 1.X, or use [my fork ](https://github.com/alexey-belous/Suave.Swagger) of the library. But it isn't available as nuget package, you can only compile it by yourself and keep this version along with your project.

**Comment by rkosafo** [comment] 2017-02-16 03:09
@alexey-belous I compiled your fork and it worked. One observation though is that when the data type is string, it is represented as an object instead

    {
        "Chars": "string",
        "Length": 0
    }

Is this an issue or it is by design?

**Comment by rflechner** [comment] 2017-03-15 21:11
Hi, really sorry for the delay.

@alexey-belous thank you very much for your help.

I am publishing the NuGet.

Regards

**Closed as completed** 2017-03-15 21:16 UTC
