### ISSUE TITLE
StackOverflow exception at webserver startup

### ISSUE THREAD

**Issue by jkone27** [rflechner/Suave.Swagger#20] opened 2017-08-16 12:36 UTC
### Description
I Get stackOverflow exception when adding a body parameter in my POST swagger configuration,
if i remove the line containing the post parameter, i get no exceptions and the program runs flawlessly

i.e. this line in the code below

```fs
    yield parameter "orderRequest" Of route (fun p -> { p with Type = (Some typeof<OrderFile>); In=Body })
```

### Repro steps
```fs

let postOrder (dc, id) =
    let request = findFileByIdAndDc id dc
    match request with
    |Some(filePath,_) ->
        postRequest dc filePath
    |None -> 
        NOT_FOUND (sprintf "order was not found: %s" id)

let createResponse =
    JsonBody<OrderFile>(fun model -> MODEL { model with OrderNumber = "" })

let api = 
        let getOrdersPart = pathScan "/%s/orders/%s" findOrderById
        let postOrdersPart = pathScan "/%s/orders/%s" postOrder
//        choose [
//            getOrdersPart ; 
//            postOrdersPart
//        ]
        swagger {

                for route in getOf getOrdersPart do
                    yield description Of route is "Search for an order file"
                    yield urlTemplate Of route is "/{distributionCenter}/orders/{orderNumber}"
                    yield parameter "distributionCenter" Of route  (fun p -> { p with Type = (Some typeof<string>); In=Path })
                    yield parameter "orderNumber" Of route  (fun p -> { p with Type = (Some typeof<string>); In=Path })

                for route in postOf postOrdersPart do
                    yield description Of route is "Post an order release request"
                    yield urlTemplate Of route is "/{distributionCenter}/orders/{orderNumber}"
                    yield route |> addResponse 200 "returns the orderRequest with assigned Id" (Some typeof<OrderFile>)
                    yield parameter "distributionCenter" Of route  (fun p -> { p with Type = (Some typeof<string>); In=Path })
                    yield parameter "orderNumber" Of route  (fun p -> { p with Type = (Some typeof<string>); In=Path })
                    yield parameter "orderRequest" Of route (fun p -> { p with Type = (Some typeof<OrderFile>); In=Body })
        }

[<EntryPoint>]
let main argv = 
  let distributionCenters = Settings.LogisticHubs
  startWebServer defaultConfig api.App 
  0

```

### Expected behavior

I should see the same behaviour as the example code nr.3 in the documentation.

### Actual behavior

StackOverflow exception at startup.

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Windows 8.1
* Latest Package on Nuget
* .NET 4.6

**Comment by rflechner** [comment] 2017-10-27 08:30
Hi,

Could you provide structure of type `OrderFile` ?

Thanks.

**Comment by jkone27** [comment] 2017-10-27 12:19
```fs
type OrderFile =
    { 
        OrderNumber: string;
        Canceled : string option;
        Packages : string option;
        RejectedItems : RejectedItem option
    }
and RejectedItem = {
        SerialNumber: string;
        NotShippedType: int;
        NotShippedNote: string option;
    }
```

**Comment by alexey-belous** [comment] 2017-11-18 12:07
Have the same issue. It seems that root cause is that in the model are option fields.

**Comment by rflechner** [comment] 2017-11-20 14:41
Hi,
Bug is fixed in this PR https://github.com/rflechner/Suave.Swagger/pull/21

Regards

**Comment by rflechner** [comment] 2017-11-20 14:48
Nuget is published here: https://www.nuget.org/packages/Suave.Swagger/2.3.0

**Closed as completed by rflechner** 2017-11-20 14:48 UTC
